annotations:
  artifacthub.io/license: AGPL-3.0
apiVersion: v2
appVersion: "v0.23.0"
description:
  Meet Plane. An open-source software development tool to manage issues,
  sprints, and product roadmaps with peace of mind.
home: https://plane.so
icon: https://plane.so/favicon/favicon-32x32.png
name: plane-helm
sources:
  - https://github.com/makeplane/plane
type: application
version: 1.3.0
dependencies:
  - name: postgresql
    version: "15.5.38"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: "20.1.7"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: minio
    version: "14.7.15"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
  - name: rabbitmq
    version: "15.0.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
