name: Release Charts

on:
  push:
    tags:
      - 1.**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: appany/helm-oci-chart-releaser@3c5d99817f3951337934478da3b1fcb0cab227a3
        with:
          name: plane-helm
          tag: ${{ github.ref_name }}
          path: ./
          registry: ghcr.io/kraudcloud
          repository: plane-helm
          registry_username: kraudcloud
          registry_password: ${{ secrets.GITHUB_TOKEN }}
